---
# tasks for iis_simple

- name: install iis
 win_feature:
  name: web-server
  state: present

- name: create site directory server
 win_file:
  path: "{{ item.path }}"
  state: directory
 with_items: "{{ iis_sites }}"

 - name: create iis site
   win_iis_website:
    name: "{{ item.name }}"
    state: started
    port: "{{ item.port }}"
    physical path: "{{ item.path }}"
   with_item: "{{ iis_sites }}"
   notify: restart iis service

 - name: open port for site on the firewall
   win_firewall_rule:
    name: "iisport{{ item.port }}"
    enable: yes
    state: present
    localport: "{{ item.port }}"
    action: allow
    direction: ln
    protocol: tcp
   with_items: "{{ iis_sites }}"

 - name: template simple website to iis_site_path as index.html
   win_template:
    src: 'index.html.j2'
    dest: '{{ item.path }}\index.html'
   with_items: "{{ iis_sites }}"

 - name: show website addresses
   debug:
    msg: "{{ item }}"
   loop:
    - http://{{ ansible_host }}:8080
    - http://{{ ansible_host }}:8081   